version: "3.8"

services:
  rich-presence:
    image: ghcr.io/aarush0101/rich-presence:master
    container_name: rich-presence
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
    restart: unless-stopped
    networks:
      - rich-presence-network

networks:
  rich-presence-network:
    driver: bridge
